### ISSUE TITLE
Enahancement: list of other open ports when importing from nmap?

### ISSUE THREAD

**Issue by Viss** [ChrisTruncer/EyeWitness#117]
It would be super handy to have, in the left hand info pane, the other ports and banners that were discovered as open on the host if eyewitness was used on an nmap xml file. It would save time having to go sift through nmap xml or text output to find additional data on that host.

**Comment by ChrisTruncer** [comment]
That's a pretty cool idea, I'll look to get that added in.

Also, didn't forget about threading, it's just going to take a little bit of figuring out how to do it properly.

**Comment by digininja** [comment]
If you decided to make the ruby one multithreaded let me know, I've done a
lot of research on it recently.

**Comment by digininja** [comment]
If you do implement this idea, probably best put it in a closed by default
block otherwise some images could end up being really tall if their servers
have lots of open ports.

**Comment by ChrisTruncer** [comment]
We'll look into if this is something that's easy to add.  I'm not certain we'll get this in, but we'll take another look now that we have 2.0 released.

**Comment by ChrisTruncer** [comment]
I think for now we will leave this closed.  I think it would really impact the output of the report for some hosts, and it would probably be easier for nmap to just be used.  If this turns out to be something people really really want, I can take another look at it.  However in the event of VHOSTS, it's going to be returning a large number of duplicate data that users may not care about.
