### ISSUE TITLE
Schmoo Branch

### ISSUE THREAD

**Issue by korang** [ChrisTruncer/EyeWitness#120]
I noticed using the schmoo branch  on Kali, with chrome as default browser, it opened the browser to take the screenshot.  Is this an expected behavior?

**Comment by korang** [comment]
Actually it appears ti opened iceweasel.  Is this still expected behavior.  Thanks

**Comment by ChrisTruncer** [comment]
Yup,

This is expected behavior.  You can still use ghost if you want, instead of using --web, you would use --headless.  However, --web (selenium) is much more stable than Ghost in all of the testing that I've performed, so I've been steering people towards using that.  But yes, it is expected behavior, it actually drives your existing web browser and uses that functionality to render the page and screenshot it.
