### ISSUE TITLE
Enhancement request - flag to disable credential check

### ISSUE THREAD

**Issue by jerichod505** [ChrisTruncer/EyeWitness#158]
Chris:
Great project, guys!  I will definitely start using this on engagements.

Would you consider adding a flag to disable the credential check?  something like a --no-creds option would be great, since there are some times where even checking for a default login is outside of the scope of the assessment.

I have done a simple workaround by renaming the signatures.txt file, but what would be great is to have that option specified on the command line so I could choose to disable it on a call-by-call basis.

I was tempted to modify the code but i am pretty python challenged.... :}

Thanks.

j.

**Comment by rvazarkar** [comment]
EyeWitness doesn't try the credentials in signatures.txt. It just displays
them in the report. The only thing that gets submitted is for sites that
have basic authentication, in which case it submits bogus values to get rid
of the popup. There's no real workaround for this because selenium has a
bug that will cause it to hang forever on basic auth prompts.

However, eyewitness does not submit anything through forms or other inputs

**Comment by ChrisTruncer** [comment]
I'll go ahead and close this out for the time being.  @jerichod505 if this isn't what you meant, just respond and let us know.

**Comment by jerichod505** [comment]
Perfect.  Thanks guys.  This answers my question.  I guess I read more into the function than was intended.  :}  Thanks for the quick response....
