### ISSUE TITLE
screenshot gets stuck

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#160]
I've managed to get the script stuck taking a web screenshot. It isn't timing out despite being left for ages. If I use curl -v I get a load of these lines:

```
* additional stuff not fine transfer.c:1037: 0 0
```

Showing the site is returning stuff which prevents the timeout but it never actually seems to finish.

If I kill EyeWitness and resume it goes back to this last entry and gets stuck again. As the resume database is already populated I'm stuck. It would be good to have a way to remove an entry from the database to prevent this.

For now, I went into the database and found the only http entry that wasn't complete and just deleted it. Resumed and the report was generated so all is good.

Doubt it is in your power, but something to detect that a shot has taken longer than expected so it can be killed would be good. I guess this is down to the Selenium or whatever is being used though.

**Comment by ChrisTruncer** [comment]
That’s a really interesting bug…  But I think you possibly nailed it on the head that I don’t know if we will be able to control this on our level, because we’re relying on output/events from the screenshotting libraries we are using.  Did you use --web?  That does use selenium, as you said.  Could you see if you run into the same issue by using --headless instead of web?  That will use phantomjs, and I’d be curious if it runs into the same issue.

Otherwise, you’re right it might be nice have an auxiliary script that would allow manipulating/deleting records from the DB if this happens.


On October 29, 2015 at 9:42:36 AM, Robin Wood (notifications@github.com) wrote:

I've managed to get the script stuck taking a web screenshot. It isn't timing out despite being left for ages. If I use curl -v I get a load of these lines:

* additional stuff not fine transfer.c:1037: 0 0

Showing the site is returning stuff which prevents the timeout but it never actually seems to finish.

If I kill EyeWitness and resume it goes back to this last entry and gets stuck again. As the resume database is already populated I'm stuck. It would be good to have a way to remove an entry from the database to prevent this.

For now, I went into the database and found the only http entry that wasn't complete and just deleted it. Resumed and the report was generated so all is good.

Doubt it is in your power, but something to detect that a shot has taken longer than expected so it can be killed would be good. I guess this is down to the Selenium or whatever is being used though.

**Comment by digininja** [comment]
It wasn't web it was headless, didn't expect --web to work as this is a
headless box but as its Kali it must have the pre-requesits so it worked.
It didn't stall on that URL, ran through fine. Looks like the headless
library is broken.

**Comment by ChrisTruncer** [comment]
OK, I'll try to get something submitted upstream soon.  Thanks for letting us know.

**Comment by digininja** [comment]
I don't think there is anything in the app to do it, but the way I'd do it
would be with an iptables rule to drop traffic to that host or port so no
connection is made.

**Comment by ChrisTruncer** [comment]
There's no way to do it from an XML file. But each time EyeWitness parses an xml file, it writes out the parsed results to a text file within the same directory. You can go into that file, remove the specific system/port combo, and then start the scan over with the parsed results.
