### ISSUE TITLE
proxy-ip not being used if invalid

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#171]
I tried to run this command and didn't realise that the port should be on its own parameter

```
./EyeWitness.py  --single http://ipchicken.com  --web --proxy-ip 192.168.0.46:808
```

The proxy was ignored and the screenshot taken directly. If the proxy is invalid then it should fail with an error, not continue regardless.

**Comment by ChrisTruncer** [comment]
Sorry I'm just now getting to this.  Do you by chance happen to have a proxy I could test with?

**Comment by digininja** [comment]
you don't need a proxy, just use something invalid like in my example and you'll get a screenshot even though you shouldn't as you said go through a proxy and it couldn't.

I think that is the case, its been a while.

**Comment by ChrisTruncer** [comment]
ha, yeah that was dumb of me.  Thanks

**Comment by ChrisTruncer** [comment]
Ok, well first thing I see here is the port isn't given with the --proxy-ip command, it's given with --proxy-port.  When I supply both of them, I am getting a connection refused due to proxy error.

It looks like --headless is about to grab server headers, but can't get source or screenshot a page.

I'm going to add in a check for if providing proxy-ip you need to add proxy-port too

**Comment by ChrisTruncer** [comment]
So looked like if only IP was provided, selenium is doing something odd and just not using the proxy.  So now an ip and port are required using the two different cli options, which will then force screenshots and website source code grabbing to be done through the proxy.
