### ISSUE TITLE
Firefox Run issue

### ISSUE THREAD

**Issue by theabraxas** [ChrisTruncer/EyeWitness#196]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Unbunto 16, Azure base image

################################################################################
#                                  EyeWitness                                  #
################################################################################

Attempting to screenshot http://xxxxxxxxxxxx
Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

## Expected behavior (vs. what you encountered)
This worked before on a previous VM (~6 months ago?) there is no GUI installed but I don't recall this error. I'm also confused because I saw, during the setup, that there was a section for PhantomJS which I assume would/should trump Firefox.

## Any additional information
This is a new image from azure, updated server, installed git, cloned your project, ran setup, and now these issues. I'm looking in to running additional cmds to do headless mode but I expect there should be a way around it as it ran well previously.

**Comment by ChrisTruncer** [comment]
EyeWitness is not able to use FireFox normally in a headless environment.
That’s why the headless option is there.  You need to use that instead of
—web.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On July 7, 2016 at 2:27:02 PM, Abraxas (notifications@github.com) wrote:

OS Used - ALL Information (architecture, linux flavor, etc.)

Unbunto 16, Azure base image
Pastebin link to error you are encountering

################################################################################
EyeWitness

################################################################################

Attempting to screenshot http://xxxxxxxxxxxx
Message: The browser appears to have exited before we could connect. If you
specified a log_file in the FirefoxBinary constructor, check it for details.
Expected behavior (vs. what you encountered)

This worked before on a previous VM (~6 months ago?) there is no GUI
installed but I don't recall this error. I'm also confused because I saw,
during the setup, that there was a section for PhantomJS which I assume
would/should trump Firefox.
Any additional information

This is a new image from azure, updated server, installed git, cloned your
project, ran setup, and now these issues. I'm looking in to running
additional cmds to do headless mode but I expect there should be a way
around it as it ran well previously.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/196>, or mute the thread
<https://github.com/notifications/unsubscribe/ABmORhoSyjA_SzgR3ZuWVfgAa8yOaY2-ks5qTWEVgaJpZM4JHd28>
.

**Comment by theabraxas** [comment]
Ahh, thanks a ton @ChrisTruncer super grateful for your project.
