### ISSUE TITLE
Switch "--add-http-ports" doesn't appear to work

### ISSUE THREAD

**Issue by mikelott** [ChrisTruncer/EyeWitness#201]
## OS Used
```
$ uname -a
Linux kali 4.4.0-kali1-686 #1 SMP Debian 4.4.2-3kali1 (2016-02-23) i686 GNU/Linux
```

## Expected behavior
Screenshot and info of web service listening port 8000.

## Any additional information
This is what I ran w/ ouput:

```
$ eyewitness --headless --single myip --no-dns --add-http-ports 8000

################################################################################
#                                  EyeWitness                                  #
################################################################################

Attempting to screenshot http://myip
[*] Hit timeout limit when connecting to http://myip, retrying
[*] Hit timeout limit when connecting to http://myip

[*] Done! Report written in the 07242016_203256 folder!
Would you like to open the report now? [Y/n]
```

Proof that port is open and service listening: output of cURL, as follows:

```
$ curl -I --http2 http://myip:8000
HTTP/1.1 302 Found
Date: Sun, 24 Jul 2016 19:02:07 GMT
Server: Apache/2.2.3 (CentOS)
X-Powered-By: PHP/5.1.6
Set-Cookie: PHPSESSID=sv7dsbvg0qg279he2jfobdb8u5; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: login.php
Connection: close
Content-Type: text/html; charset=UTF-8
```

I'm either misunderstanding how the switch is called, or it's being ignored.

Mike

**Comment by ChrisTruncer** [comment]
Hi, thanks for sending this over.  It's working as intended, but I obviously failed on the documentation portion of this, so I'll try to help explain.

The --add-http-ports is used when parsing an XML file.  By default it searches for a few ports, 80, 8080, and one other I am forgetting off the top of my head.  When you use the --add-http-ports, it will add the port to search for when parsing an XML file.  With all that said, by default EyeWitness will parse the files and also search for any service that is being reported to be HTTP or HTTPS and auto-scan those as well.

Funny thing about this report too, is it looks like I removed the -no-dns flag accidentally when upgrading the XML parsing.  That flag is used when parsing the XML file, it will grab the IP address instead of the dns address identified in the xml file.  I'll need to get that added back in.

So, hope that this helps explain the features.

**Comment by mikelott** [comment]
Hey Chris

Thanks for the information on this. Much appreciated :)

Mike
