### ISSUE TITLE
Message: Can't load the profile

### ISSUE THREAD

**Issue by freeload101** [ChrisTruncer/EyeWitness#210]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Tried ubuntu 64 ( Ubuntu 16.04.1 LTS ) and kali-linux-2016.1-amd64.iso 
Python 2.7.12
CHANGELOG:    Released..: 2.2

when I use the -f switch it basically just hangs. 

./EyeWitness.py --sinngle "http://go.com" --web --show-selenium --resolve ( firefox pops up with a blank window dumps png's in /tmp but errors with)  

Message: Can't load the profile. Profile Dir: /tmp/tmpltLp4Q If you specified a log_file in the FirefoxBinary constructor, check it for details.

./EyeWitness.py --single "http://kpmg.com" --headless --show-selenium --resolve

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x7ff8e00d5810>> ignored

## Expected behavior (vs. what you encountered)

the project folders dont have anything in them just the --web sort of works with stuff in /tmp

## Any additional information

I would love  to contribute and mreger other password tools/databases to support EyeWitness! Thanks!

**Comment by ChrisTruncer** [comment]
Just a piece of info, the --resolve flag is only used when parsing an xml input file.

I tested the first command you have (but fixed the "single" typo), and everything is working on my end.  I can't seem to re-create an error. 

For the second command, --show-selenium won't work because it's using phantomjs.  The command --show-selenium only shows the browser when using --web.  

The only thing that I've seen that causes the error to show that you are referencing is that you are missing the phantomjs binary.  Please check the bin folder and make sure you have it.  You need to run the setup script because it will download it.

**Comment by ChrisTruncer** [comment]
Closing since I haven't heard back.  Please just re-comment if you have anything else.
