### ISSUE TITLE
Issue with --all-protocols flag in Eyewitness

### ISSUE THREAD

**Issue by str4n63r** [ChrisTruncer/EyeWitness#244]
Hello,

I was trying to take screenshots of all protocols on few IPs and tried giving Nmap output(.xml) to Eyewitness as input which resulted in above error mentioned in Pastebin link. Help appreciated.

Thanks & regards,
str4n63r

**Comment by ChrisTruncer** [comment]
This sounds like your XML input is invalid, and something is wrong with it.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On February 5, 2017 at 11:07:08 PM, Venkata Sateesh Netti (
notifications@github.com) wrote:

#OS Used - Kali 2.0, 32-Bit
#Pastebin link - http://pastebin.com/qFPYzJbq

Hello,

I was trying to take screenshots of all protocols on few IPs and tried
giving Nmap output(.xml) to Eyewitness as input which resulted in above
error mentioned in Pastebin link. Help appreciated.

Thanks & regards,
str4n63r

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/244>, or mute the thread

**Comment by str4n63r** [comment]
#OS Used - Kali 2.0, 32-Bit
#Pastebin link - http://pastebin.com/aRKVMhjw

Hello @ChrisTruncer ,

Thanks for letting me know about the invalid XML file because I did tried with an invalid XML file. But please check out the error popped up this time even though I tried with correct Nmap Output(.xml) file.

Thanks & regards,
str4n63r

**Comment by str4n63r** [comment]
Hello @ChrisTruncer ,

Was able to identify that now and thanks for letting me know.  But now this new error pops up even though I am trying with proper Nmap Output (.xml) file.
[http://pastebin.com/5dimCL4Y](http://pastebin.com/5dimCL4Y)

Thanks & regards,
str4n63r

**Comment by ChrisTruncer** [comment]
There might still be a problem with your XML file


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On February 6, 2017 at 12:08:28 PM, Venkata Sateesh Netti (
notifications@github.com) wrote:

Hello @ChrisTruncer <https://github.com/ChrisTruncer> ,

Was able to identify that now and thanks for letting me know. But now this
new error pops up even though I am trying with proper Nmap Output (.xml)
file.
http://pastebin.com/5dimCL4Y

Thanks & regards,
str4n63r

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/244#issuecomment-277780576>,
or mute the thread

**Comment by str4n63r** [comment]
No @ChrisTruncer . This time I  rechecked and tried with Nmap GUI Version(Zenmap) and it gave me a clear view of all the services running.  By any chance this issue is causing because of **--all-protocols** flag? Because I am planning to take screenshot of every possible service running.

**Comment by ChrisTruncer** [comment]
it shouldn't really be the cause of it, can you try running it one protocol at a time?

**Comment by str4n63r** [comment]
Even when I am just trying RDP and VNC individually using Nmap Output(.xml) file it is giving the  error message mentioned in below link.

**Command Used:** ./Eyewitness.py -x output.xml --vnc (or) --rdp
**Sample Output:** [http://pastebin.com/5dimCL4Y](http://pastebin.com/5dimCL4Y)

**Comment by ChrisTruncer** [comment]
Can you upload the xml file here?


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On February 7, 2017 at 7:01:56 AM, Venkata Sateesh Netti (
notifications@github.com) wrote:

Even when I am just trying RDP and VNC individually using Nmap Output(.xml)
file it is giving the error message mentioned in below link.

*Command Used:* ./Eyewitness.py -x output.xml --vnc (or) --rdp
*Sample Output:* http://pastebin.com/5dimCL4Y

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/244#issuecomment-278007941>,
or mute the thread

**Comment by str4n63r** [comment]
As of now it is working fine with individual protocol.  Thanks for the help.

**Comment by ChrisTruncer** [comment]
Again, can you load the XML file here?

**Comment by str4n63r** [comment]
@ChrisTruncer Please check out the Nmap XML output in the below link.

**XML Output:** [http://pastebin.com/m3u7kF0X](http://pastebin.com/m3u7kF0X)

**Comment by ChrisTruncer** [comment]
This works for me, I am able to parse that XML file without an issue.

**Comment by str4n63r** [comment]
Below is the output I received after executing **./Eywitness.py -x 57.xml --all-protocols**

Starting Web Requests (3 Hosts)
Message: Service geckodriver unexpectedly exited. Status code was: -11
Message: Service geckodriver unexpectedly exited. Status code was: -11
Message: Service geckodriver unexpectedly exited. Status code was: -11

Starting VNC/RDP Requests (4 Hosts)
Xlib:  extension "RANDR" missing on display ":1001".
[*] Connecting to 172.25.15.57 (RDP)
[*] Error connecting to 172.25.15.57:5900
[*] Connecting to 172.25.15.57 (RDP)
[*] Error connecting to 172.25.15.57:5900
Finished in 4.3358540535 seconds

[*] Done! Report written in the EyeWitness/02142017_123351 folder!
Would you like to open the report now? [Y/n] python: Fatal IO error 0 (Success) on X server :1001.

**Comment by ChrisTruncer** [comment]
Are you running this headlessly through an XServer?

Unfortunately, I don't know what to say, because I am not encountering this issue when using the same XML file.

**Comment by str4n63r** [comment]
I will try reinstalling the whole package anyway. Thanks for the help.
