### ISSUE TITLE
Optimize image storage

### ISSUE THREAD

**Issue by ethicalhack3r** [ChrisTruncer/EyeWitness#245]
Just an idea.

EyeWitness stores an screenshot per HTTP response. This leads to a lot of duplicate screenshots, for example, default IIS pages. If seven hosts had default IIS pages, EyeWitness will save seven separate screenshots, although all seven are exactly the same.

The solution would be to use something like (https://huddle.github.io/Resemble.js/) which would compare the two screenshots, if 100% match to a previous one, no need to store it.

This will save hard drive space, decrease time moving results around, and increase HTML report loading speed.

**Comment by digininja** [comment]
Is this really a problem? I've done scans that have gone to 5-6 pages and
the total storage required isn't that much.

**Comment by ethicalhack3r** [comment]
Not a problem, but an optimisation/improvement and maybe an interesting challenge :)

**Comment by ethicalhack3r** [comment]
Looks like it could be as simple as comparing image MD5 hashes. They match on my machine, so no need for complicated external library. I thought timestamps in exif data may not have allowed this but I was wrong.

**Comment by ChrisTruncer** [comment]
So, for the splash pages, or others, it’s actually the exact md5?  If
that’s the case, that makes sense, but I also would assume there would be
some random artifact or something that would throw off a hash.


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On February 8, 2017 at 8:56:13 AM, Ryan Dewhurst (notifications@github.com)
wrote:

Looks like it could be as simple as comparing image MD5 hashes. They match
on my machine, so no need for complicated external library. I thought
timestamps in exif data may not have allowed this but I was wrong.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/245#issuecomment-278368679>,
or mute the thread

**Comment by ethicalhack3r** [comment]
Yup, the exact MD5. I also assumed that the MD5 hashes of the screenshots would not match, but it turns out that they do.

**Comment by ChrisTruncer** [comment]
ok, I'll have to think about the best way to logically handle this within the code. I don't think it's a huge problem, but it is something that could be done to help reduce space.

**Comment by ChrisTruncer** [comment]
Ideally, this should now be solved! Let me know if you encounter any issues, but it grabs the md5 hashes of each image, compares them with each other, and if there's a match, it modifies the report to use just one image, keeps that one, and then deletes the duplicates.
