### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by junkoji** [ChrisTruncer/EyeWitness#258]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Blackarch Linux eyewitness was pre-installed

## Pastebin link to error you are encountering
https;//pastebin.com/xn13jDK7

## Expected behavior (vs. what you encountered)
Tried running setup,sh file in the setup directory

## Any additional information
also was wondering where to locate phantomjs.

**Comment by ChrisTruncer** [comment]
I don’t support BlackArch linux. Also, the setup script is designed to work
with apt, not pacman.

Thanks


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On March 30, 2017 at 7:41:07 AM, junkoji (notifications@github.com) wrote:

OS Used - ALL Information (architecture, linux flavor, etc.)

Blackarch Linux eyewitness was pre-installed
Pastebin link to error you are encountering

https;//pastebin.com/xn13jDK7
Expected behavior (vs. what you encountered)

Tried running setup,sh file in the setup directory
Any additional information

also was wondering where to locate phantomjs.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/258>, or mute the thread

**Comment by junkoji** [comment]
Ok,Thank you very much for your prompt reply
