### ISSUE TITLE
PhantomJS not being recognized

### ISSUE THREAD

**Issue by Slad3G** [ChrisTruncer/EyeWitness#267]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali 2017.1

## Pastebin link to error you are encountering
[*] Error: You are missing your phantomjs binary!
 [*] Please run the setup script!

Quick FYI, setup script has been run.

## Expected behavior (vs. what you encountered)
--headless should execute

## Any additional information
--web switch does work fine

**Comment by ChrisTruncer** [comment]
I have a clean Kali VM, I just ran the setup script and headless does work.

Please make sure you are running the setup script from within the setup directory

**Comment by Slad3G** [comment]
I sent you a screen cap of my install and results.

**Comment by ChrisTruncer** [comment]
Just saw it,

Can you run EyeWitness from within the EyeWitness directory vs. calling it
from outside of that folder?


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On May 26, 2017 at 3:34:19 PM, Slade (notifications@github.com) wrote:

I sent you a screen cap of my install and results.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisTruncer/EyeWitness/issues/267#issuecomment-304392920>,
or mute the thread

**Comment by Slad3G** [comment]
That works, good enough for me if it is for you.

**Comment by ChrisTruncer** [comment]
Yup, that's the way I've always had it work.

Thanks!
