### ISSUE TITLE
AttributeError: 'HTTPTableObject' object has no attribute '_headers'

### ISSUE THREAD

**Issue by okiwoki** [ChrisTruncer/EyeWitness#293]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali Rolling 2

## Pastebin link to error you are encountering

https://pastebin.com/6PJzu8ru

## Expected behavior (vs. what you encountered)

Report should be created after screenshotting services

## Any additional information

EyeWitness was ran from its working directory

Parameters used:
./EyeWitness.py -f ~/hosts.txt -d ~/results/client --prepend-https --timeout 30 --max-retries 2 --threads 15 --no-prompt --headless

**Comment by ChrisTruncer** [comment]
Can you see if this happened on a specific host? Or can you re-create this with all scans (such as google)?

**Comment by ChrisTruncer** [comment]
closing for no response

**Comment by xyzkab** [comment]
hei @ChrisTruncer i'm having the same issue here.
first i wanna say Thanks for sharing such a great tool!
let me describe what i do first;

i do screenshot for **2852** subdomains http and https so the total is **5704**
```
root@eyewitness:eyeWitness# sqlite3 ~/l33t/outputs/ew.db 
SQLite version 3.16.2 2017-01-06 16:32:41
Enter ".help" for usage hints.
sqlite> select count(*) from http where complete=1;
5704
sqlite> select count(*) from http where complete=0;
0
```
i try to catch the error at ``headers`` method in ``modules/object.py`` like this:
```
def headers(self):
    try:
        return self._headers
    except AttributeError:
        id = self.id
        scr = os.path.relpath(self.screenshot_path,self.root_path)
        src = os.path.relpath(self.source_path, self.root_path)
        print "GET_ERROR| id: {} | scr_path: {} | scr_path: {}".format(id,scr,src)
```
but then of course it fails at ``create_table_html`` method since it was trying to extract the ``items`` from ``headers`` while i return ``None`` by capturing the error
```
Traceback (most recent call last):
  File "./EyeWitness.py", line 624, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 552, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/l33t/eyeWitness/modules/reporting.py", line 200, in sort_data_and_write
    html += obj.create_table_html()
  File "/l33t/eyeWitness/modules/objects.py", line 246, in create_table_html
    for key, value in self.headers.items():
AttributeError: 'NoneType' object has no attribute 'items'
```
at least i get what the id is **2033** and the subdomain host that failed by extracting the source path since the format is ``http.subdomainhost.txt`` so i can lookup the host manually. turns out i can resolve the subdomain with browser or curl. i still have no idea why and what causing the missing ``_headers`` attribute.
oh the id before **2033** have the ``_headers`` attribute

can you point me to right direction if i just know more where to look maybe i can help.
i'm sorry i can't disclose what the subdomain address.
