### ISSUE TITLE
Report Usability Concerns

### ISSUE THREAD

**Issue by TheNaterz** [ChrisTruncer/EyeWitness#307]
I wanted to address concerns that I have with the new HTML reporting style. Looking through the commit history, it looks like a lot of work went into updating how the reports look and how users can navigate them. I really do appreciate the amount of work that's been dedicated to this. I've really enjoyed using EyeWitness as my go-to for looking through a large volume of web services on pentests at a glance.

That being said, and I've got to be honest here, the new reports are awful and navigating them is frustrating.

In no particular order, here are the problem areas I've been experiencing:

- The images are huge. The previous reports also had this, but at the very least, items were split up into several pages and it wasn't that bad scrolling through each page. I believe the reports would be vastly improved if the images were scaled down, or at the very least have a user-friendly option for this. Scrolling through the reports would be much faster. The image hyperlink could still point to the full 1200x675 images.

- The pages for a section (e.g. High Value Targets) are only at the bottom of the section. If I want to look through all items for a section, I have to scroll to the bottom of the section, scroll up to the top to view those items, then scroll all the way back down to change to the next page. If page numbers were located at both the top and bottom, I wouldn't have to scroll past the items I just viewed. This gets exacerbated if I choose to view more items per page.

- A section with 20+ pages makes it hard to get to the middle pages. If I have a section with 20 pages and I want to see page 10, I have to go through and click next 10 times to get there. The previous reports had each page number linkable from the top. It didn't look amazing, but at least I could go to the exact page I wanted in one click. With the new style, I believe something like a page search bar to go directly to a certain page would be nice.

- Changing a page shifts all contents either up or down (including the page index), making it difficult to quickly go through pages. Again, if I have 20+ pages and I want to get to page 10, I have to play "follow the page index" for each page in order to get there. If I go too quickly, I end up accidentally clicking an image and have to go back. Going to a new page should retain the position of the page index.

- Each section has its own search bar, but there isn't a global search bar. As an example, ideally, all Apache Tomcat installation pages show up under High Value Targets, but this isn't always the case, and sometimes they go under Unclassified or some other section. A global search bar would be helpful in displaying those items across all sections.

- Clicking a URL hyperlink should default to opening in a new tab. Maybe this is just a personal preference, but I don't believe that clicking a URL on the report should take me away from the report. In my opinion, it should open a tab and move my focus there.

Another suggestion to improve the reports would be to take the Table of Contents and make it a floating bar. If images are reduced in size, then the right side becomes blank and could be filled with this bar instead. This floating bar could also have the currently viewable section's search bar and possibly even page index.

I like the direction with where these reports are going, but I think these are areas that can be improved. I'm very open to having a dialogue on current and future design decisions. If people think that these new reports are fine and I'm just a lunatic, that's also fine hahaha. If there's a better place to discuss these things, please let me know.

Thank you!

**Comment by ChrisTruncer** [comment]
I'll go through and try to address these one at a time, but also want to speak to this overall. This is something I do on my own time, by myself. This is time spent when I could be doing other things. Coming in and making a lot of "suggestions" without offering any code in the form of a pull request can be frustrating from my perspective. You're saying that aren't happy with the work I put in, and need to fix it all. Granted, I know you didn't say it like that, but it can be a bit frustrating reading this. My counterpoint to you would be, do you have a pull request that "fixes" the problems you are having? I would be more than happy to review them, and likely would accept them into the project.

Going in order:

1. I can look into images being too large, I believe they are currently set to be a percentage of the browser, but would need to check.
2. It might help to have page numbers at the top and bottom, but from a usability perspective, the bottom was chosen since I would imagine most people would scroll to the bottom of a page/section and access the next page (like a normal website)
3. I don't think I plan on having a page search bar, I think best option will be to directly click on the page number you want to go to (if possible), or click on the highest page number until the page you want to see shows up.
4. This is based on the size of the images/websites. This isn't based on code running in the web page. I'm hesitant to hard code table sizes because there is the likelihood of a lot of wasted space.
5. This could be fairly useful, will have to see the ease of which it could be added in.
6. I'll check this, this should ideally be an easy add-in.

You have a lot of suggestions, but it will likely take a lot of work, and while I am definitely supporting this tool, the amount of work you want seen in this isn't something I have the time to put in. I'm more than happy to review any pull requests from you with suggested changes as that can be done quickly.

**Comment by TheNaterz** [comment]
I completely understand that this is something you do in your own time and I'm not looking to get these things addressed immediately or even in a timely fashion. I really just wanted to provide feedback and start a dialogue and unfortunately Github doesn't have a great place for that. The tone of the issue may have come across as accusatory or hostile, but I assure you I didn't intend for that. These are really just initial thoughts.

I do intend to push PRs. Like you, I can only do that when I have time. If I post PRs that you don't believe would improve anything, that wastes both of our time and I'd like to avoid that.

Thank you again for all the work you've put into this tool and thank you for taking time to talk about the points I brought up. I'll go ahead and close.

**Comment by ChrisTruncer** [comment]
Ultimately, I agree that there are improvements that can be made. I also, personally think, that where it is now is a step forward from where it was. But I am more than willing to work on updates and review PRs to get everything even more improved.
